"""
Unit and integration tests for train.py (R1 requirements).
Covers:
- run_pipeline end-to-end execution
- Synthetic fallback data generation when data_path is missing
- Dual artifact synchronization (output_artifact -> model.joblib)
- Live reload verification and sample probability bounds [0.0, 1.0]
- CLI argument parsing and flags (--data-path, --output, --max-buckets, --target-col, --fico-col)
- Error handling on invalid CLI options
"""

import sys
import subprocess
import joblib
import pytest
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline

from train import run_pipeline


class TestTrainPipelineExecution:
    """Tests for run_pipeline execution, synchronization, and smoke verification."""

    def test_run_pipeline_with_existing_data(self, tmp_path, monkeypatch, synthetic_loan_data_small):
        """Validates end-to-end execution of run_pipeline with an existing dataset."""
        monkeypatch.chdir(tmp_path)
        data_csv = "small_loans.csv"
        synthetic_loan_data_small.to_csv(data_csv, index=False)
        artifact_name = "test_artifact.joblib"

        champion = run_pipeline(
            data_path=data_csv,
            output_artifact=artifact_name,
            max_fico_buckets=3,
            target_col='default',
            fico_col='FICO_score'
        )

        assert isinstance(champion, Pipeline)
        assert (tmp_path / artifact_name).exists()
        assert (tmp_path / "model.joblib").exists()

    def test_run_pipeline_synthetic_fallback(self, tmp_path, monkeypatch):
        """When data_path is missing, run_pipeline must generate synthetic loans and complete successfully."""
        monkeypatch.chdir(tmp_path)
        missing_csv = "auto_generated_loans.csv"
        artifact_name = "fallback_artifact.joblib"

        assert not (tmp_path / missing_csv).exists()

        champion = run_pipeline(
            data_path=missing_csv,
            output_artifact=artifact_name,
            max_fico_buckets=3,
            target_col='default',
            fico_col='FICO_score'
        )

        assert (tmp_path / missing_csv).exists(), "Dataset should be generated by fallback mechanism"
        generated_df = pd.read_csv(missing_csv)
        assert len(generated_df) == 10000
        assert isinstance(champion, Pipeline)

    def test_dual_artifact_synchronization(self, tmp_path, monkeypatch, synthetic_loan_data_small):
        """Validates that output_artifact is synchronized to model.joblib with numerical parity."""
        monkeypatch.chdir(tmp_path)
        data_csv = "sync_data.csv"
        synthetic_loan_data_small.to_csv(data_csv, index=False)
        custom_artifact = "custom_champion.joblib"

        run_pipeline(
            data_path=data_csv,
            output_artifact=custom_artifact,
            max_fico_buckets=3,
            target_col='default',
            fico_col='FICO_score'
        )

        assert (tmp_path / custom_artifact).exists()
        assert (tmp_path / "model.joblib").exists()

        # Reload both and confirm identical predictions on holdout sample
        p1 = joblib.load(custom_artifact)
        p2 = joblib.load("model.joblib")

        sample_X = synthetic_loan_data_small.drop(columns=['default']).iloc[:10]
        prob1 = p1.predict_proba(sample_X)
        prob2 = p2.predict_proba(sample_X)
        np.testing.assert_allclose(prob1, prob2, atol=1e-7)

    def test_run_pipeline_same_artifact_name(self, tmp_path, monkeypatch, synthetic_loan_data_small):
        """When output_artifact is already 'model.joblib', synchronization branch is bypassed safely."""
        monkeypatch.chdir(tmp_path)
        data_csv = "same_name_data.csv"
        synthetic_loan_data_small.to_csv(data_csv, index=False)

        champion = run_pipeline(
            data_path=data_csv,
            output_artifact="model.joblib",
            max_fico_buckets=3,
            target_col='default',
            fico_col='FICO_score'
        )
        assert (tmp_path / "model.joblib").exists()
        assert isinstance(champion, Pipeline)

    def test_smoke_test_scoring_and_bounds(self, tmp_path, monkeypatch, synthetic_loan_data_small):
        """Validates that reloaded pipeline produces probabilities strictly bounded in [0.0, 1.0]."""
        monkeypatch.chdir(tmp_path)
        data_csv = "smoke_data.csv"
        synthetic_loan_data_small.to_csv(data_csv, index=False)
        artifact = "smoke_artifact.joblib"

        run_pipeline(
            data_path=data_csv,
            output_artifact=artifact,
            max_fico_buckets=3,
            target_col='default',
            fico_col='FICO_score'
        )

        loaded = joblib.load(artifact)
        sample = synthetic_loan_data_small.drop(columns=['default']).iloc[[0]]
        prob = float(loaded.predict_proba(sample)[0, 1])
        pred = int(loaded.predict(sample)[0])

        assert 0.0 <= prob <= 1.0
        assert pred in {0, 1}


class TestTrainCLIArguments:
    """Tests for train.py command line interface flags and subprocess execution."""

    def test_train_cli_help(self):
        """train.py --help must display argument descriptions and exit with code 0."""
        res = subprocess.run(
            [sys.executable, "train.py", "--help"],
            capture_output=True,
            text=True
        )
        assert res.returncode == 0
        assert "--data-path" in res.stdout
        assert "--output" in res.stdout
        assert "--max-buckets" in res.stdout
        assert "--target-col" in res.stdout
        assert "--fico-col" in res.stdout

    def test_train_cli_execution_with_flags(self, tmp_path, synthetic_loan_data_small):
        """train.py executed with CLI flags must parse arguments and produce artifacts."""
        data_csv = tmp_path / "cli_data.csv"
        synthetic_loan_data_small.to_csv(data_csv, index=False)
        output_art = tmp_path / "cli_model.joblib"

        cmd = [
            sys.executable, "train.py",
            "--data-path", str(data_csv),
            "--output", str(output_art),
            "--max-buckets", "3",
            "--target-col", "default",
            "--fico-col", "FICO_score"
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        assert res.returncode == 0, f"train.py failed with error:\n{res.stderr}"
        assert output_art.exists()

    def test_train_cli_invalid_argument_fails(self):
        """train.py called with unrecognized options must exit with code 2 (argparse error)."""
        res = subprocess.run(
            [sys.executable, "train.py", "--non-existent-option-xyz"],
            capture_output=True,
            text=True
        )
        assert res.returncode != 0
        assert "unrecognized arguments" in res.stderr
